import { BudgetRow } from "@/interfaces";
  
 export const budgetData: Array<BudgetRow> = [
        {
            date: "2021-01-01",
            store: "Walmart",
            withdrawal: 50,
            deposit: 0,
            balance: 950,
            category: "Groceries",
            notes: "Groceries",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-02",
            store: "Amazon",
            withdrawal: 100,
            deposit: 0,
            balance: 850,
            category: "Electronics",
            notes: "Electronics",
            id: crypto.randomUUID(),

        },
        {
            date: "2021-01-03",
            store: "Paycheck",
            withdrawal: 0,
            deposit: 2000,
            balance: 2850,
            category: "January paycheck",
            notes: "January paycheck",
            id: crypto.randomUUID(),

        },
        {
            date: "2021-01-04",
            store: "Shell Gas Station",
            withdrawal: 65.32,
            deposit: 0,
            balance: 2784.68,
            category: "Gas",
            notes: "Fuel",
            id: crypto.randomUUID(),

        },
        {
            date: "2021-01-05",
            store: "Michaels",
            withdrawal: 42.50,
            deposit: 0,
            balance: 2742.18,
            category: "Crafts",
            notes: "Yarn and craft supplies",
            id: crypto.randomUUID(),

        },
        {
            date: "2021-01-06",
            store: "Whole Foods",
            withdrawal: 87.43,
            deposit: 0,
            balance: 2654.75,
            category: "Groceries",
            notes: "Weekly groceries",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-07",
            store: "Sam's Club",
            withdrawal: 156.78,
            deposit: 0,
            balance: 2497.97,
            category: "Groceries",
            notes: "Bulk groceries",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-08",
            store: "Starbucks",
            withdrawal: 5.75,
            deposit: 0,
            balance: 2492.22,
            category: "Coffee",
            notes: "Morning coffee",
            id: crypto.randomUUID(),

        },
        {
            date: "2021-01-09",
            store: "Target",
            withdrawal: 34.22,
            deposit: 0,
            balance: 2458.00,
            category: "Household",
            notes: "Household items",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-10",
            store: "Chevron",
            withdrawal: 52.80,
            deposit: 0,
            balance: 2405.20,
            category: "Gas",
            notes: "Fuel",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-11",
            store: "Joann Fabrics",
            withdrawal: 28.99,
            deposit: 0,
            balance: 2376.21,
            category: "Crafts",
            notes: "Fabric and thread",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-12",
            store: "Chipotle",
            withdrawal: 12.50,
            deposit: 0,
            balance: 2363.71,
            category: "Food",
            notes: "Lunch",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-13",
            store: "Home Depot",
            withdrawal: 95.40,
            deposit: 0,
            balance: 2268.31,
            category: "Home Improvement",
            notes: "Paint and supplies",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-14",
            store: "Walmart",
            withdrawal: 63.17,
            deposit: 0,
            balance: 2205.14,
            category: "Groceries",
            notes: "Groceries and supplies",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-15",
            store: "BP Gas Station",
            withdrawal: 58.90,
            deposit: 0,
            balance: 2146.24,
            category: "Gas",
            notes: "Fuel",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-16",
            store: "IKEA",
            withdrawal: 147.66,
            deposit: 0,
            balance: 1998.58,
            category: "Furniture",
            notes: "Shelving units",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-17",
            store: "McDonald's",
            withdrawal: 8.45,
            deposit: 0,
            balance: 1990.13,
            category: "Food",
            notes: "Breakfast",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-18",
            store: "Best Buy",
            withdrawal: 129.99,
            deposit: 0,
            balance: 1860.14,
            category: "Electronics",
            notes: "USB cables and adapter",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-19",
            store: "Trader Joe's",
            withdrawal: 71.38,
            deposit: 0,
            balance: 1788.76,
            category: "Groceries",
            notes: "Weekly groceries",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-20",
            store: "Speedway",
            withdrawal: 55.00,
            deposit: 0,
            balance: 1733.76,
            category: "Gas",
            notes: "Fuel and snacks",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-21",
            store: "Michaels",
            withdrawal: 35.67,
            deposit: 0,
            balance: 1698.09,
            category: "Crafts",
            notes: "Paint and canvas",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-22",
            store: "Costco",
            withdrawal: 142.50,
            deposit: 0,
            balance: 1555.59,
            category: "Groceries",
            notes: "Bulk shopping",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-23",
            store: "Paycheck",
            withdrawal: 0,
            deposit: 2500,
            balance: 4055.59,
            category: "January paycheck",
            notes: "Paycheck deposit",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-24",
            store: "Shell Gas Station",
            withdrawal: 61.45,
            deposit: 0,
            balance: 3994.14,
            category: "Gas",
            notes: "Fuel",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-25",
            store: "Whole Foods",
            withdrawal: 94.82,
            deposit: 0,
            balance: 3899.32,
            category: "Groceries",
            notes: "Organic produce and dairy",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-26",
            store: "Joann Fabrics",
            withdrawal: 52.19,
            deposit: 0,
            balance: 3847.13,
            category: "Crafts",
            notes: "Knitting needles and wool",
            id: crypto.randomUUID(),
        },
        {
            date: "2021-01-27",
            store: "Target",
            withdrawal: 45.68,
            deposit: 0,
            balance: 3801.45,
            category: "Household",
            notes: "Kitchen supplies",
            id: crypto.randomUUID(),
        }
    ];